version: '3.3'

networks: #top level field
  security:
    external: true
  proxy:
    external: true

services:
  gateway:
    image: spring-gateway
    networks:
      - default
      - security
      - proxy
    labels:
      - "traefik.frontend.rule=Host:gateway.docker.localhost"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"
      - "traefik.frontend.passHostHeader=true"