server:
  port: 9000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

kc:
  base-url: http://keycloak:8080/auth
  realm: master
  realm-url: ${kc.base-url}/realms/${kc.realm}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
