version: '3.3' 

volumes:
  mysql_data:
    driver: local

networks: #top level field
  security:
    external: true
  proxy:
    external: true

services:    
     
  keycloak:
    image: jboss/keycloak:4.8.3.Final
    networks:
      - default
      - proxy
      - security
    labels:
      - "traefik.frontend.rule=Host:keycloak.docker.localhost"
      - "traefik.port=8080"
      - "traefik.docker.network=proxy"
    environment:
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    depends_on:
      - mysql
      
  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql